const bearer =
  "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJlMWYwOWFiYTlmNWQ1YmVjNjY1OGFmMjg4ZGZiNThkYyIsInN1YiI6IjY1Mjk1MzMwNjI5YjJjMDEzOWE5MWZmOCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.mrqlt8sliwgRCTkgSla0ub4rhtI8oljltNtdkeMulUM";

export default bearer;
